import { contextHash, validateAnalysis, type SentenceAnalysis } from '@cet-reading/contracts';
import type { RuntimeConfig } from '@cet-reading/contracts/config';
import type { Pool } from 'pg';

const BACKGROUND_PRIORITY = 1;
const MAX_ACTIVE_JOBS = 8;

type Candidate = {
  id: string;
  owner_id: string;
  source_text: string;
  source_hash: string;
  paper_id: string | null;
  article_id: string | null;
  title: string;
  previous_sentence: string | null;
  next_sentence: string | null;
  paragraph_index: number;
  sentence_index: number;
};

type CandidateWithContext = Candidate & {
  context_json: { title: string; previousSentence: string | null; nextSentence: string | null };
  context_hash: string;
};

type Cursor = { owner_id: string; paragraph_index: number; sentence_index: number };

type ExistingCache = {
  sentence_id: string;
  source_hash: string;
  context_hash: string;
  analysis_json: unknown;
};

type ExistingJob = {
  sentence_id: string;
  source_hash: string;
  context_hash: string;
  status: string;
};

function sleep(ms: number, signal: AbortSignal) {
  return new Promise<void>(resolve => {
    const onAbort = () => {
      clearTimeout(timer);
      signal.removeEventListener('abort', onAbort);
      resolve();
    };
    const timer = setTimeout(() => {
      signal.removeEventListener('abort', onAbort);
      resolve();
    }, ms);
    signal.addEventListener('abort', onAbort, { once: true });
    if (signal.aborted) onAbort();
  });
}

async function loadCandidates(pool: Pool, limit: number, cursor: Cursor | null) {
  const cursorClause = cursor ? 'AND (owner_id, paragraph_index, sentence_index) > ($1::text, $2::integer, $3::integer)' : '';
  const params = cursor ? [cursor.owner_id, cursor.paragraph_index, cursor.sentence_index, limit] : [limit];
  const limitParameter = cursor ? '$4' : '$1';
  const result = await pool.query<Candidate>(
    `WITH ordered AS (
       SELECT s.id, COALESCE(s.paper_id, s.article_id) AS owner_id,
              s.source_text, s.source_hash, s.paper_id, s.article_id,
              COALESCE(p.title, n.title, '') AS title,
              lag(s.source_text) OVER w AS previous_sentence,
              lead(s.source_text) OVER w AS next_sentence,
              s.paragraph_index, s.sentence_index
       FROM sentences s
       LEFT JOIN papers p ON p.id = s.paper_id
       LEFT JOIN news_articles n ON n.id = s.article_id
       WHERE (p.status = 'published' OR n.status = 'published')
       WINDOW w AS (
         PARTITION BY s.paper_id, s.article_id
         ORDER BY s.paragraph_index, s.sentence_index
       )
     )
     SELECT * FROM ordered
     WHERE TRUE ${cursorClause}
     ORDER BY COALESCE(paper_id, article_id), paragraph_index, sentence_index
     LIMIT ${limitParameter}`,
    params,
  );
  return result.rows.map(row => {
    const context_json = {
      title: row.title,
      previousSentence: row.previous_sentence,
      nextSentence: row.next_sentence,
    };
    return { ...row, context_json, context_hash: contextHash(context_json) };
  });
}

async function loadExisting(pool: Pool, candidates: CandidateWithContext[], config: RuntimeConfig) {
  if (!candidates.length) return { caches: new Map<string, SentenceAnalysis>(), jobs: new Map<string, ExistingJob>() };
  const ids = candidates.map(candidate => candidate.id);
  const [cacheRows, jobRows] = await Promise.all([
    pool.query<ExistingCache>(
      `SELECT sentence_id, source_hash, context_hash, analysis_json
       FROM sentence_analyses
       WHERE sentence_id = ANY($1::text[]) AND prompt_version = $2
         AND model = $3 AND mode = $4 AND status = 'succeeded'`,
      [ids, config.promptVersion, config.model, config.mode],
    ),
    pool.query<ExistingJob>(
      `SELECT sentence_id, source_hash, context_hash, status
       FROM analysis_jobs
       WHERE sentence_id = ANY($1::text[]) AND prompt_version = $2
         AND model = $3 AND mode = $4`,
      [ids, config.promptVersion, config.model, config.mode],
    ),
  ]);
  const byId = new Map(candidates.map(candidate => [candidate.id, candidate]));
  const caches = new Map<string, SentenceAnalysis>();
  for (const row of cacheRows.rows) {
    const candidate = byId.get(row.sentence_id);
    if (!candidate || caches.has(row.sentence_id) ||
        candidate.source_hash !== row.source_hash || candidate.context_hash !== row.context_hash) continue;
    try {
      caches.set(row.sentence_id, validateAnalysis(candidate.source_text, row.analysis_json));
    } catch {
      // Invalid historical results must be regenerated by the queue.
    }
  }
  const jobs = new Map<string, ExistingJob>();
  for (const row of jobRows.rows) {
    const candidate = byId.get(row.sentence_id);
    if (candidate && candidate.source_hash === row.source_hash && candidate.context_hash === row.context_hash) {
      const previous = jobs.get(row.sentence_id);
      if (!previous || previous.status === 'succeeded') jobs.set(row.sentence_id, row);
    }
  }
  return { caches, jobs };
}

async function enqueueBackgroundSentence(pool: Pool, sentence: CandidateWithContext, config: RuntimeConfig) {
  const client = await pool.connect();
  const key = [sentence.id, sentence.source_hash, sentence.context_hash, config.promptVersion, config.model, config.mode];
  try {
    await client.query('BEGIN');
    await client.query('SELECT pg_advisory_xact_lock(hashtext($1))', [
      `analysis:${config.mode}:${config.model}:${config.promptVersion}:${sentence.id}`,
    ]);
    const existing = await client.query<{ id: string; status: string }>(
      `SELECT id, status FROM analysis_jobs
       WHERE sentence_id = $1 AND source_hash = $2 AND context_hash = $3
         AND prompt_version = $4 AND model = $5 AND mode = $6
       ORDER BY updated_at DESC LIMIT 1`, key,
    );
    const row = existing.rows[0];
    if (row?.status === 'pending' || row?.status === 'running' || row?.status === 'failed') {
      await client.query('ROLLBACK');
      return false;
    }
    if (row?.status === 'succeeded') {
      await client.query(
        `UPDATE analysis_jobs SET status = 'pending', priority = $2,
         error_message = NULL, attempts = 0, lease_expires_at = NULL,
         started_at = NULL, finished_at = NULL, next_attempt_at = NOW(), updated_at = NOW()
         WHERE id = $1`, [row.id, BACKGROUND_PRIORITY],
      );
    } else {
      await client.query(
        `INSERT INTO analysis_jobs
           (sentence_id, source_text, source_hash, context_hash, context_json,
            prompt_version, model, mode, status, priority, next_attempt_at)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'pending', $9, NOW())`,
        [sentence.id, sentence.source_text, sentence.source_hash, sentence.context_hash,
          JSON.stringify(sentence.context_json), config.promptVersion, config.model, config.mode, BACKGROUND_PRIORITY],
      );
    }
    await client.query('COMMIT');
    return true;
  } catch (error) {
    await client.query('ROLLBACK').catch(() => undefined);
    // Another enqueue path may have won the per-sentence lock between scans.
    if ((error as { code?: string }).code === '23505') return false;
    throw error;
  } finally {
    client.release();
  }
}

export async function fillBackgroundQueue(pool: Pool, config: RuntimeConfig, cursor: Cursor | null = null) {
  if (!config.backfillEnabled || config.mode !== 'ai' || config.backfillTarget === 0) {
    return { queued: 0, nextCursor: cursor, scanHasMore: false };
  }
  const counts = await pool.query<{ total: number; background: number }>(
    `SELECT COUNT(*) FILTER (WHERE status IN ('pending', 'running'))::integer AS total,
            COUNT(*) FILTER (WHERE status IN ('pending', 'running') AND priority <= $4)::integer AS background
     FROM analysis_jobs
     WHERE mode = $1 AND model = $2 AND prompt_version = $3`,
    [config.mode, config.model, config.promptVersion, BACKGROUND_PRIORITY],
  );
  const total = counts.rows[0]?.total ?? 0;
  const background = counts.rows[0]?.background ?? 0;
  const capacity = Math.min(config.backfillTarget - background, MAX_ACTIVE_JOBS - total);
  if (capacity <= 0) return { queued: 0, nextCursor: cursor, scanHasMore: false };

  const candidateLimit = Math.max(50, capacity * 10);
  const candidates = await loadCandidates(pool, candidateLimit, cursor);
  if (!candidates.length) return { queued: 0, nextCursor: null, scanHasMore: false };
  const { caches, jobs } = await loadExisting(pool, candidates, config);
  let queued = 0;
  let lastExamined: Cursor = candidates[0]!;
  for (const candidate of candidates) {
    if (queued >= capacity) break;
    lastExamined = candidate;
    if (caches.has(candidate.id)) continue;
    const job = jobs.get(candidate.id);
    if (job?.status === 'pending' || job?.status === 'running' || job?.status === 'failed') continue;
    if (await enqueueBackgroundSentence(pool, candidate, config)) queued += 1;
  }
  return {
    queued,
    nextCursor: {
      owner_id: lastExamined.owner_id,
      paragraph_index: lastExamined.paragraph_index,
      sentence_index: lastExamined.sentence_index,
    },
    // Cached pages are common after a restart. Scan the next page immediately
    // instead of leaving worker slots idle for a full scheduler interval.
    scanHasMore: queued < capacity && candidates.length === candidateLimit,
  };
}

export async function runBackfillScheduler(pool: Pool, config: RuntimeConfig, signal: AbortSignal) {
  if (!config.backfillEnabled || config.mode !== 'ai') return;
  let cursor: Cursor | null = null;
  while (!signal.aborted) {
    let scanHasMore = false;
    try {
      const result = await fillBackgroundQueue(pool, config, cursor);
      cursor = result.nextCursor;
      scanHasMore = result.scanHasMore;
      if (result.queued) process.stdout.write(`Background analysis queued ${result.queued} sentence(s).\n`);
    } catch (error) {
      process.stderr.write(`Background analysis scheduler: ${error instanceof Error ? error.message : String(error)}\n`);
    }
    if (!scanHasMore) await sleep(config.backfillIntervalMs, signal);
  }
}
